Repository Crystal-Creations-GbR/crystal-components, pull requests merged in 2024-03, with the labels that each got.

#38 feat: add component `CItemListGroup`
  src/components/CItemListGroup.vue
  src/index.ts
  src/nuxt.mjs
Labels: type:feat

#40 refactor: use vuetify blueprint `md3`
  vuetify-options.ts
Labels: type:refactor

#41 ci: remove branch `next`
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release_beta.yml
Labels: type:ci

#42 feat: add component `CNavigationDrawer`
  src/components/CNavigationDrawer.vue
  src/index.ts
  src/nuxt.mjs
Labels: type:feat

#43 build(deps-dev): add `storybook-i18n` as dev-dependency
  package.json
  yarn.lock
Labels: scope:deps-dev, type:build

#46 test: add `CSnackbar` stories
  stories/CSnackbar.stories.ts
Labels: type:test

#52 refactor: add storybook helper functions
  src/storybook-helper.ts
  stories/CSnackbar.stories.ts
Labels: type:refactor

#47 feat: add component `CCard`
  src/components/CCard.vue
  src/index.ts
  src/nuxt.mjs
  stories/CCard.stories.ts
Labels: type:feat

#51 refactor: remove uppercase from buttons as default to fit md3-spec
  vuetify-options.ts
Labels: type:refactor

#49 feat: add component `CCardDialog`
  src/components/CCardDialog.vue
  src/index.ts
  src/nuxt.mjs
  stories/CCardDialog.stories.ts
Labels: type:feat

#48 feat: add component `CSettingsItem`
  src/components/CSettingsItem.vue
  src/index.ts
  src/nuxt.mjs
  stories/CSettingsItem.stories.ts
Labels: type:feat

#54 feat: emit `close` event when the dialog is closed
  src/components/CCardDialog.vue
Labels: type:feat

#55 feat: add `CPasswordInput`
  src/components/CPasswordInput.vue
  src/index.ts
  src/locales/de.json
  src/nuxt.mjs
  stories/CPasswordInput.stories.ts
Labels: type:feat

#56 fix: fix scrolling inside a `CCardDialog`
  src/components/CCard.vue
  src/components/CCardDialog.vue
  stories/CCardDialog.stories.ts
Labels: type:fix

#58 fix: allow `undefined` as model-value for `c-password-input`
  src/components/CPasswordInput.vue
Labels: type:fix

#59 fix: align subtitle to center in `CSettingsItem`
  src/components/CSettingsItem.vue
Labels: type:fix

#57 fix: remove `maxWidth` from `CCardDialog`
  src/components/CCardDialog.vue
  stories/CCardDialog.stories.ts
Labels: type:fix

#64 feat: add `color` property to `CCard` and `CCardDialog`
  src/components/CCard.vue
  src/components/CCardDialog.vue
  stories/CCard.stories.ts
Labels: type:feat

#66 fix: fix responsiveness of card actions
  src/components/CCard.vue
Labels: type:fix

#67 feat: add component`CMultiOptionButton`
  src/components/CMultiOptionButton.vue
  src/index.ts
  src/nuxt.mjs
  stories/CMultiOptionButton.stories.ts
Labels: type:feat

#68 feat: support `activator` slot and property in `CCardDialog`
  src/components/CCardDialog.vue
Labels: type:feat
